# String Operators and String methods
name="shravana"
print("Name is=",name)
# Slicing
print("name[0:8:2]=",name[0:8:2])
print("name[1::]=",name[1::])
print("name[:4]=",name[:4])
print("name[0:8]=",name[0:8])
print("name[0:]=",name[0:])
print("name[-1:-9:-1]=",name[-1:-9:-1])
print("name[:len(name):2]=",name[:len(name):2])
print("name[3:3]=",name[3:3])
print("name[3:10]=",name[3:10])
# Methods
newname="shravana".upper()
print('"shravana".upper()=',newname)
changename=newname.lower()
print("newname.lower()=",changename)
print("'Yes do it now'.title()=",'Yes do it now'.title())
print("'#23?'.isalpha()",'#23?'.isalpha())
print("'india12'.isalpha()=",'india12'.isalpha())
print('"123".isdigit()=',"123".isdigit())
print('"indrani".isdigit()=',"indrani".isdigit())
print('"hi girls".isspace()=',"hi girls".isspace())
print('"    ".isspace()=',"   ".isspace())
print('"I love you".capitalize()=',"i love you".capitalize())
print('"i love my job".isalnum()=',"i love my job".isalnum())
print('"India123".isalnum()=',"India123".isalnum())
print('len("indrani")=',len("indrani"))
print("ord('A')=",ord('A'))
print("ord('a')=",ord('a'))
print("chr(66)=",chr(66))
print("chr(98)=",chr(98))
word="pranaam"
print('"pranaam".find("na")=',"pranaam".find("na"))
print('"pranaam".find("na",4)=',"pranaam".find("na",4))
print('"pranaam".find("Na")=',"pranaam".find("Na"))
print('"pranaam".index("na")=',"pranaam".index("na"))
#print('"pranaam".index("na",4)=',"pranaam".index("na",4))
print('"coconut".count("co")=',"coconut".count("co"))
print('"coconut".count("co",2)=',"coconut".count("co",2))
print('"coconut".count("co",1,3)=',"coconut".count("co",1,3))
print('"coconut milk".partition("nut")=',"coconut milk".partition("nut"))
print('"coconut".partition("but")=',"coconut".partition("but"))
print('"Hi ".join("Five")=',"Hi ".join("Five "))
print('"coconut".rstrip("rst")=',"coconut".rstrip("rst"))
print('"   coconut   ".rstrip()=',"   coconut   ".rstrip())
print('"   coconut   ".lstrip()=',"   coconut   ".lstrip())
print('"coconut".lstrip("rcst")=',"rcstoconut".lstrip("rcst"))
print('"IndraNI Kundu".swapcase()=',"IndraNI Kundu".swapcase())
print("I am a computer teacher".split())
# Operators
print('"chandrani"+"ghosh"=',"chandrani"+"ghosh")
#print("chandrani"+3)
print('"chandrani"*3=',"chandrani"*3) # replication operator
print('3*"hi"=',3*"hi")
print('"hi"=="hi"=',"hi"=="hi")
print('"hi"=="five"=',"hi"=="five")
print('"hi"=="HI"=',"hi"=="HI")
print('"hi"!="HI"=',"hi"!="HI")
print('"abc"<"ABC"=',"abc"<"ABC")
print('"ABC"<"abc"=',"ABC"<"abc")
print('"ABC"<"ABD"=',"ABC"<"ABD")
#print("2"*"3")
#print("25"/"5")
print ('"ind" in "indrani"=',"ind" in "indrani")
print('"IN" in "indrani"=',"IN" in "indrani")
print('"in" not in "indrani"=',"in" not in "indrani")
print(input("enter a word")+"trial"+"ooty"*3)